version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 578813437933.dkr.ecr.us-east-1.amazonaws.com
      - echo Updating kubeconfig for Amazon EKS...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t htech .
      - docker tag htech:latest 578813437933.dkr.ecr.us-east-1.amazonaws.com/htech:latest
  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 578813437933.dkr.ecr.us-east-1.amazonaws.com/htech:latest
      - aws eks --region us-east-1 update-kubeconfig  --name terraform-eks-demo
      - kubectl delete -f HomeApp.yaml
      - kubectl apply -f HomeApp.yaml
