---
apiVersion: v1
kind: Namespace
metadata:
  name: game-204873
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-204873
  name: deployment-2048100
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-2048101
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-2048101
    spec:
      containers:
      - image: 578813437933.dkr.ecr.us-east-1.amazonaws.com/htech
        imagePullPolicy: Always
        name: app-2048101
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  namespace: game-204873
  name: service-2048102
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-2048101
